name: Snyk Full Scan

on:
  push:
    branches:
      - staging
  pull_request:
  workflow_dispatch:

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Optional: Display what Snyk will detect
    - name: Print detected projects
      run: snyk test --all-projects --dry-run

    # Dependency scan for each .csproj file
    - name: Monitor Contacts.API dependencies
      run: snyk monitor --file=Contacts.API/Contacts.API.csproj --project-name="Contacts.API"

    - name: Monitor Contacts.Domain dependencies
      run: snyk monitor --file=Contacts.Domain/Contacts.Domain.csproj --project-name="Contacts.Domain"

    # Dockerfile scan (adjust path if necessary)
    - name: Docker scan
      run: |
        docker build -t contacts-api -f Contacts.API/Dockerfile .
        snyk container monitor contacts-api --project-name="Contacts.API Docker"

    # Static Code Analysis
    - name: Code Analysis (Snyk Code)
      run: snyk code monitor --project-name="Contacts.API Code"
