name: Snyk Scan

on:
  push:
    branches:
      - staging

jobs:
  snyk:
    name: Run Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # use your actual version

      - name: Change to Contacts directory and restore dependencies
        working-directory: ./Contacts
        run: dotnet restore Contacts.sln

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk scan on solution
        working-directory: ./Contacts
        run: snyk test --file=Contacts.sln --severity-threshold=medium

      - name: Monitor project in Snyk Dashboard
        working-directory: ./Contacts
        run: snyk monitor --file=Contacts.sln

      - name: Build Docker image
        run: docker build -t contacts-app -f Contacts/Dockerfile .

      - name: Snyk Container Scan
        run: snyk container test contacts-app --severity-threshold=medium

      - name: Monitor Docker image in Snyk
        run: snyk container monitor contacts-app
